apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    spec:
      containers:
        - name: gateway
          image: minhdtb/storeo-gateway:latest
          ports:
            - containerPort: 4000
              name: gateway
          env:
            - name: COMMON_SERVICE
              value: common.storeo.svc.cluster.local
